project: ape-transformers-mse
name: pde-mc-b-mse

batch_size: 8
max_epochs: 100

trainer:
    base_learning_rate: 4.0e-5
    batch_size: ${batch_size}
    scale_lr: False
    params:
        _file: config/default_trainer_args.yaml
        max_epochs: ${max_epochs}
        accumulate_grad_batches: 8
        precision: bf16-mixed

num_train_timesteps: 20

pipelines:
    default:
      target: src.sampler.pipeline.VideoPipelineDirect

patch_size: 4
in_channels: 2
out_channels: 2
sample_size: 128

sigma_min: 1e-4

model:
    target: src.core.training.SingleStepSupervised
    params:
        model:
          target: src.core.mixed_channels.PDETransformer
          params:
            sample_size: ${sample_size}
            in_channels: ${in_channels}
            out_channels: ${out_channels}
            type: PDE-B
            patch_size: ${patch_size}
            periodic: True
            carrier_token_active: False
        monitor: val/loss_epoch
        ckpt_path: ${runtime.checkpoint_dir}
        image_key: 0
        optimizer: adamw

unrolling_steps: 1
test_unrolling_steps: 29

data:
  _file: config/ape_2d/data/multi_task_norm.yaml

frequency_log_images: 100
frequency_log_metrics: 100
frequency_store_pipelines: 100

callbacks:
  _file: config/default_callbacks.yaml
  ema:
    target: src.callback.EMA
    params:
      decay: 0.999
  images:
    target: src.callback.MultiTaskVideoLoggerCustom
    params:
      frequency: ${frequency_log_images}
      num_frames: 29
      num_inference_steps: 40
      test_only: True
      prepare_plots:
        target: src.data.pbdl_module.prepare_plots
  simulation:
    target: src.callback.Simulation2DMetricLoggerCustom
    params:
      frequency: ${frequency_log_metrics}
      batch_size: ${batch_size}
      num_frames: 29
      num_inference_steps: 40
      test_only: True
      metric_config:
        _file: config/default_simulation_metrics.yaml
  emagrad:
    target: src.callback.EmaGradClip
    params:
      ema_coef1: 0.9
      ema_coef2: 0.99
      max_norm_ratio: 2.0
      clip_norm_ratio: 1.1



