rmse:
  target: src.metric.SimulationRMSE3D
  params:
    frequency: 1
    num_tasks: 30
    max_length: 100
    dataset_names: ${data.params.dataset_names}
mse:
  target: src.metric.SimulationMSE3D
  params:
    frequency: 1
    num_tasks: 30
    max_length: 100
    dataset_names: ${data.params.dataset_names}
mae:
  target: src.metric.SimulationMAE3D
  params:
    frequency: 1
    num_tasks: 30
    max_length: 100
    dataset_names: ${data.params.dataset_names}